#!/bin/sh
# Remove all of the json files from the migration target area,
# leaving only those checked into git.
#
JSON=${GIT_REPO}/blt/migration/json
rm -f ${JSON}/g2/*.json
rm -f ${JSON}/ignition/*.json
