#!/bin/sh
# Remove all of the json files from the migration target area,
# leaving only those checked into git.
#
PROCS=${GIT_REPO}/blt/migration/procs
rm -rf ${PROCS}/g2/*
rm -rf ${PROCS}/ignition/*
