#!/bin/sh
# Remove all of the json files from the migration target area,
# leaving only those checked into git.
#
BIN=`pwd`
REPO=~/Development/ils/src/blt/json
rm -f ${REPO}/g2/*.json
rm -f ${REPO}/ignition/*.json
