#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
BIN=`pwd`
SVN=~/Development/ils/svn/EMChemicals/Migration/
REPO=~/Development/ils/src/blt/json
mkdir -p $REPO/g2
mkdir -p $REPO/ignition
cp ${SVN}/Vistalon/Exports/DiagnosticToolkit/json/*.json $REPO/g2
