#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
SVN=${SVN_REPO}/EMChemicals
PROCS=${GIT_REPO}/blt/migration/procs
mkdir -p ${PROCS}/g2/api
mkdir -p ${PROCS}/g2/escorez/calculation
mkdir -p ${PROCS}/g2/vistalon/calculation
mkdir -p ${PROCS}/ignition/api
mkdir -p ${PROCS}/ignition/escorez/calculation
mkdir -p ${PROCS}/ignition/vistalon/calculation
cd ${SVN}/Migration/Escorez/Exports\ from\ G2/diagToolkit/calculationMethods
cp *.txt ${PROCS}/g2/escorez/calculation
cp ${SVN}/G2Artifacts/Source\ code/vist-monitoring/procedures/CALC*.txt ${PROCS}/g2/vistalon/calculation
cp ${SVN}/G2Artifacts/Source\ code/vist-monitoring/procedures/DO_*.txt ${PROCS}/g2/vistalon/calculation
cp ${SVN}/G2Artifacts/Source\ code/vist-monitoring/procedures/PROD-MOONEY*.txt ${PROCS}/g2/vistalon/calculation
cp ${SVN}/G2Artifacts/Source\ code/em-diag-toolkit/procedures/OUTPUT-MSG-CORE.txt ${PROCS}/g2/api
