#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
SVN=${SVN_REPO}/EMChemicals/Migration/
JSON=${GIT_REPO}/blt/migration/json
mkdir -p $JSON/g2
mkdir -p $JSON/ignition
cp ${SVN}/Vistalon/Exports/DiagnosticToolkit/json/*.json $JSON/g2
