#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
SVN=${SVN_REPO}/EMChemicals/Migration/
JSON=${GIT_REPO}/blt/migration/json
mkdir -p $JSON/g2/escorez/diagrams
mkdir -p $JSON/g2/gline
mkdir -p $JSON/g2/vistalon
mkdir -p $JSON/ignition/escorez/diagrams
mkdir -p $JSON/ignition/vistalon
cp ${SVN}/BRPP_G-Line/Exports\ From\ G2/diagToolkit/json/*.json $JSON/g2/gline
cp ${SVN}/Escorez/Exports\ From\ G2/diagToolkit/json/*.json $JSON/g2/escorez
cp ${SVN}/Escorez/Exports\ From\ G2/diagToolkit/standAloneDiagrams/json/*.json $JSON/g2/escorez/diagrams
cp ${SVN}/Vistalon/Exports\ From\ G2/DiagnosticToolkit/json/*.json $JSON/g2/vistalon
