#!/bin/sh
#  Data migration conversion script
# -- options for root.class: APPLICATION, DIAGRAM
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: migrate <inpath> <outpath>"
	exit 2
fi
BLT=${GIT_REPO}/blt
SFC=${GIT_REPO}/sfc
LIB=${GIT_REPO}/external/lib
JAR=${LIB}/blt-migration.jar
DB=${SFC}/migration/mdb/conversion.db
cat $1 | java -cp ${JAR} -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB} > $2
