#!/bin/sh
# Clear existing artifacts, copy latest G2 exports from svn area,
# then process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
./clear-json
BLT=${GIT_REPO}/blt
APP=$BLT/migration/migrate
INDIR=$BLT/migration/json/g2
OUTDIR=$BLT/migration/json/ignition
mkdir -p $INDIR
mkdir -p $OUTDIR/gline
mkdir -p $OUTDIR/escorez
mkdir -p $OUTDIR/vistalon
OUTFIL=migration.out
cd $BLT/migration
./copy-json
echo "======================== G Line ================================"
cd $INDIR/gline
for fil in *.json
do
	echo "Processing $fil ..."
    $APP ${INDIR}/gline/$fil ${OUTDIR}/gline/$fil
done
echo "======================== Escorez ================================"
cd $INDIR/escorez
for fil in *.json
do
	echo "Processing $fil ..."
    $APP $INDIR/escorez/$fil $OUTDIR/escorez/$fil
done
echo "======================== Vistalon ================================"
cd $INDIR/vistalon
for fil in *.json
do
	echo "Processing $fil ..."
    $APP $INDIR/vistalon/$fil $OUTDIR/vistalon/$fil 
done
