#!/bin/sh
#  Use this version when debugging a single file.
#
BLT=~/Development/ils/src/blt
#FIL=dirtSimpleApplication
#FIL=dirtSimpleApplicationWithConnections
#FIL=crxProductQuality
#FIL=polyFlyingSwitch
#FIL=oneBadFamily
#FIL=vfuProductQuality
FIL=vfuProductQuality
INDIR=$BLT/json/g2
OUTDIR=$BLT/json/ignition
mkdir -p $OUTDIR
$BLT/migration/migrate $INDIR/$FIL.json $OUTDIR/$FIL.json
