#!/bin/sh
# Clear existing artifacts, copy latest G2 exports from svn area,
# then process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
BLT=${GIT_REPO}/blt
APP=$BLT/migration/migrate
INDIR=$BLT/migration/json/g2
OUTDIR=$BLT/migration/json/ignition
mkdir -p $INDIR
mkdir -p $OUTDIR
cd $BLT/migration
./clear-json
./copy-json
echo "======================== Escorez ================================"
cd $INDIR/escorez
for fil in *.json
do
	echo "Processing $fil ..."
    $APP $INDIR/escorez/$fil $OUTDIR/escorez/$fil
done
echo "======================== Vistalon ================================"
cd $INDIR/vistalon
for fil in *.json
do
	echo "Processing $fil ..."
    $APP $INDIR/vistalon/$fil $OUTDIR/vistalon/$fil
done
