#!/bin/sh
# Process all of the json files in the repository "g2" area.
# -- use the translation variant for FInalDiagnosis calculations
# Save the results in the json storate area for ignition.
#
BLT=${GIT_REPO}/blt
PROCS=${BLT}/migration/procs
OUTDIR=${PROCS}/ignition/xom/vistalon
cd $BLT/migration
./clear-procs
./copy-procs
echo "Processing Vistalon Calculation Methods"
mkdir -p $OUTDIR
./translate-cstr all
./translate-crx all
cd ${PROCS}/ignition
cp -a project ${GIT_REPO}/xom-python/XOM_Python/src
echo "Translated procedures copied to XOM-PYTHON repository. Checkin and commit."
