#!/bin/sh
#  Procedure translation script
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: translate <file> <outdir>"
	exit 2
fi
cd ${GIT_REPO}/blt
BLT=`pwd`
SFC=${GIT_REPO}/sfc
LIB=${GIT_REPO}/external/lib
JAR=${LIB}/g2-translation.jar
DB=${SFC}/migration/mdb/conversion.db
OUTDIR=$2
mkdir -p ${OUTDIR}
java -cp ${JAR} -Dlog.level=DEBUG com.ils.python.translation.G2ProcedureTranslator $1 ${OUTDIR} ${DB} 
