#!/bin/sh
#  Use this version when debugging a single file.
#
BLT=~/Development/ils/repo/blt
FIL=CALC-BALER-TEMP-PROBLEM-OUTPUT-GDA.txt
DIR=${BLT}/migration/g2procs/fd
${BLT}/migration/translate $DIR/$FIL
