#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
BLT=~/Development/ils/src/blt
APP=${BLT}/migration/translate
cd ${BLT}/migration/g2procs/fd
for fil in *.txt
do
	echo "Processing $fil..."
    $APP $fil
done
