#!/bin/sh
# Translate methods used in the CSTR calc methods
# Process the .txt files in the process repository "g2" area.
# If the argument is "all", then all the files are processed.
# If the argument is "next" then the current file is processed
# and deleted. Then the next file is processed.
#
# We start with raw G2 exports. Convert, then save the
# results in the procedure storage area for ignition.
#
OPT="one"
if [ $# -gt 0 ]
then
    OPT=$1
fi

MIGRATION=${GIT_REPO}/blt/migration
FIL=CALC-CSTR_ML_PROBLEM-OUTPUT-GDA.txt
FIL="$FIL CALC-CSTR_C2_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_ENB_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_DC2_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_DENB_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_STAB_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_OIL_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_POLYSPLIT_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_CA_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_DML_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL CALC-CSTR_MLR_PROBLEM-OUTPUT-GDA.txt"
FIL="$FIL PROD-MOONEY-GDA.txt"

DIR=${MIGRATION}/procs/g2/vistalon/calculation
OUTDIR=${MIGRATION}/procs/ignition/vistalon/calculation
cd $DIR
for file in $FIL
do
	if [ -f $DIR/$file ]
	then
	    echo "Processing $file..."
	    ${MIGRATION}/translate.calc $DIR/$file $OUTDIR
	fi
	if [ $OPT == "all" ]
	then
		continue
	elif [ $OPT == "one" ]
	then
		exit
	else
		rm $DIR/$file
		OPT="one"
	fi
done
