#!/bin/sh
#  Build a database for translation of diagnostics toolkit 
# procedures - in particular FinalDiagnosis calculation.
#
#  -- must be run in the same directory as the insert script.
#
#!/bin/sh
#set -x
DB=lookup.db
REPO_ROOT=~/Development/ils/repo
BIN=$REPO_ROOT/blt/migration/tdb
TARGETDIR=$REPO_ROOT/blt/migration/tdb
mkdir -p ${TARGETDIR}


cd ${TARGETDIR}
rm -f $DB
sqlite3 $DB < ${BIN}/createTables.sql
sqlite3 $DB < ${BIN}/insertClassMap.sql
sqlite3 $DB < ${BIN}/insertEnumerations.sql
sqlite3 $DB < ${BIN}/insertProcedures.sql
