#!/bin/sh
#  Use this version when debugging a single file.
#
BLT=${GIT_REPO}/blt
#FIL=dirtSimpleApplication
#FIL=dirtSimpleApplicationWithConnections
FIL=crxProductQuality
#FIL=polyFlyingSwitch
#FIL=oneBadFamily
#FIL=vfuProductQuality
#FIL=cstrProductQuality
INDIR=$BLT/migration/json/g2
OUTDIR=$BLT/migration/json/ignition
mkdir -p $OUTDIR
$BLT/migration/migrate $INDIR/$FIL.json $OUTDIR/$FIL.json
