#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
fil=CRX-WARNINGS.txt
BLT=${GIT_REPO}/blt
PROCS=${BLT}/migration/procs
APP=$BLT/migration/translate.calc
cd $BLT/migration
INDIR=${PROCS}/g2/vistalon/calculations
OUTDIR=${PROCS}/ignition/vistalon
echo "Processing $fil ..."
$APP $INDIR/$fil ${OUTDIR}
