#!/bin/sh
# Translate a single method used in the poly rate change calc methods
#  - we start from the top and work down testing one-at-a-time
#
MIGRATION=${GIT_REPO}/blt/migration
FIL=DO_SPLIT_RATE_CHG-GDA.txt
FIL=DO_RATE_CHNG-GDA.txt
FIL=DO_SERIES_RATE_CHG-GDA.txt
FIL=DO_SINGLE_RATE_CHG-GDA.txt
DIR=${MIGRATION}/procs/g2/vistalon/calculation
OUTDIR=${MIGRATION}/procs/ignition
${MIGRATION}/translate.calc $DIR/$FIL $OUTDIR
