#!/bin/sh
# Translate a single method used in the poly rate change calc methods
#  - we start from the top and work down testing one-at-a-time
#
MIGRATION=${GIT_REPO}/blt/migration
FIL=DO_SPLIT_RATE_CHG-GDA
#FIL=DO_RATE_CHNG-GDA
#FIL=DO_SERIES_RATE_CHG-GDA
#FIL=DO_SINGLE_RATE_CHG-GDA
DIR=${MIGRATION}/procs/g2/vistalon
OUTDIR=${MIGRATION}/procs/ignition/vistalon
${MIGRATION}/translate.calc $DIR/$FIL $OUTDIR
