#!/bin/sh
# Remove files from the G2 and Ignition areas
# in order to slim down the set that we're actively
# working on ...
#
BIN=`pwd`
REPO=~/Development/ils/repo/blt/workspace/BLT_Migration/json
G2=${REPO}/g2
IGNITION=${REPO}/ignition
VETTED=${REPO}/ignition-vetted
mkdir -p ${G2}
mkdir -p ${IGNITION}
mkdir -p ${VETTED}
cd ${VETTED}
for fil in *.json
do
	rm -f ${G2}/$fil
	rm -f ${IGNITION}/$fil
done
