#!/bin/sh
# Move selected JSON files from the raw G2 area
# in order to slim down the set that we're actively
# working on ...
#
BIN=`pwd`
REPO=~/Development/ils/repo/blt/workspace/BLT_Migration/json
mkdir -p ${REPO}/g2
cd ${REPO}/g2
for fil in
