#!/bin/sh
#  Data migration conversion script
# -- options for root.class: APPLICATION, DIAGRAM
# -- options for log.level:  INFO,DEBUG,TRACE
#
BIN=`pwd`
#FIL=dirtSimpleApplication
FIL=dirtSimpleApplicationWithMultipleFamiliesAndProblems
LIB=$BIN/../../external/lib
JAR=${LIB}/blt-migration.jar
MIGRATION=$BIN/../workspace/BLT_Migration/json/application
DB=${BIN}/db/conversion.db
# Use for debugging - ruins output file however.
#cat ${MIGRATION}/$FIL-g2.json | java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB} > ${MIGRATION}/$FIL.json
cat ${MIGRATION}/$FIL-g2.json | java -cp ${JAR} -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB} > ${MIGRATION}/$FIL.json
