#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
BLT=~/Development/ils/repo/blt
APP=$BLT/setup/migrate
INDIR=$BLT/workspace/BLT_Migration/json/g2
OUTDIR=$BLT/workspace/BLT_Migration/json/ignition
mkdir -p $INDIR
mkdir -p $OUTDIR
cd $INDIR
for fil in *.json
do
	echo "Processing $fil..."
    $APP $INDIR/$fil $OUTDIR/$fil
done
