#!/bin/sh
#  Use this version when debugging a single file.
#
BLT=~/Development/ils/repo/blt
#FIL=dirtSimpleApplication
#FIL=dirtSimpleApplicationWithMultipleProblems1
FIL=dsa1
INDIR=$BLT/workspace/BLT_Migration/json/g2
OUTDIR=$BLT/workspace/BLT_Migration/json/ignition
mkdir -p $OUTDIR
$BLT/setup/migrate $INDIR/$FIL.json $OUTDIR/$FIL.json
