#!/bin/sh
#  Use this version when debugging a single file.
#
BLT=~/Development/ils/repo/blt
FIL=dirtSimpleApplicationWithConnections
#FIL=crxProductQuality
INDIR=$BLT/json/g2
OUTDIR=$BLT/json/ignition
mkdir -p $OUTDIR
$BLT/setup/migrate $INDIR/$FIL.json $OUTDIR/$FIL.json
