#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
BIN=`pwd`
SVN=~/Development/ils/svn/EMChemicals/G2Artifacts/DiagnosticDiagramExports/Samples
REPO=~/Development/ils/repo/blt/workspace/BLT_Migration/json
mkdir -p $REPO/g2
mkdir -p $REPO/ignition
cp "$SVN"/*.json $REPO/g2
