#!/bin/sh
# Copy the JSON files from svn into our project
# for viewing in Eclipse.
#
BIN=`pwd`
SVN=~/Development/ils/svn/EMChemicals/G2Artifacts/DiagnosticDiagramExports
REPO=~/Development/ils/repo/blt/workspace/BLT_Migration/json
mkdir -p $REPO/g2
mkdir -p $REPO/ignition
cp ${SVN}/Samples/*.json $REPO/g2
cp ${SVN}/Vistalon/*.json $REPO/g2
cp ${REPO}/g2-gold/*.json ${REPO}/g2
