#!/bin/sh
#  Build a database for migration of diagnostics applications. Copy into the migration
#  directory of the project tree.
#
#  -- must be run in the same directory as the insert script.
#
#!/bin/sh
#set -x
DB=conversion.db
REPO_ROOT=~/Development/ils/repo
BIN=$REPO_ROOT/blt/setup/db
TARGETDIR=$REPO_ROOT/blt/migration
mkdir -p ${TARGETDIR}


cd ${TARGETDIR}
rm -f $DB
sqlite3 $DB < ${BIN}/createTables.sql
sqlite3 $DB < ${BIN}/insertClasses.sql
sqlite3 $DB < ${BIN}/insertAttributes.sql
sqlite3 $DB < ${BIN}/insertProperties.sql
