INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('FeedbackMethod ', 'Feedback Method', 'Technique used to combine multiple recommandations used for the same output');
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('GroupRampMethod', 'Group Ramp Method', NULL);
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('LtSelTargetType', 'Lab Selector Target Type', 'Lab Data Toolkit - Type of the selector target');
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('RampType', 'RampType', 'IO Ramp Type');
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('RtLimitSource', 'Recipe Toolkit Limit Source', 'Values are Constant, Recipe, ?');
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('RtLimitType', 'Recipe Toolkit Limit Type', NULL);
INSERT INTO LookupType (LookupTypeCode, LookupTypeName, LookupTypeDescription) VALUES ('WindowPosition', 'Window Display Position', 'Position for displaying a window');
INSERT INTO LtHDAInterface (InterfaceId, InterfaceName) VALUES (1001, 'PHD-HDA');
INSERT INTO RoleTranslation (IgnitionRole, WindowsRole) VALUES ('Admin', 'Admin');
INSERT INTO RoleTranslation (IgnitionRole, WindowsRole) VALUES ('Admin', 'Administrator');
INSERT INTO RoleTranslation (IgnitionRole, WindowsRole) VALUES ('AE', 'AE');
INSERT INTO RoleTranslation (IgnitionRole, WindowsRole) VALUES ('Operator', 'Operator');
INSERT INTO QueueMessageStatus (StatusId, Severity, MessageStatus, Color) VALUES (1, 1, 'Info', 'white');
INSERT INTO QueueMessageStatus (StatusId, Severity, MessageStatus, Color) VALUES (2, 2, 'Warning', 'yellow');
INSERT INTO QueueMessageStatus (StatusId, Severity, MessageStatus, Color) VALUES (3, 3, 'Error', 'red');
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (1, 'DOWNLOAD', 'Recipe Download LogX', NULL, 2.5, 'bottomLeft', 0, 1, 1);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (4, 'RECOMMENDATIONS', 'Recommendations from the Diagnostic Toolkit ', '2020-10-02 12:00:01', 10, 'center', 0, 0, 0);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (8, 'XO1TEST', 'Test Console Messages', '2020-10-02 12:02:01', 1.5, 'topLeft', 0, 0, 0);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (9, 'LABDATA', 'Lab Data Messages', NULL, 10, 'center', 0, 0, 0);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (15, 'Test', 'A Queue for Testing', '2020-10-03 09:12:11', 2.5, 'topLeft', 0, 0, 0);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (16, 'SFCS', 'A Queue for SFCs', '2020-10-03 11:11:00', 1.5, 'center', 0, 1, 1);
INSERT INTO QueueMaster (QueueId, QueueKey, Title, CheckpointTimestamp, AutoViewSeverityThreshold, Position, AutoViewAdmin, AutoViewAE, AutoViewOperator) VALUES (22, 'LABFEEDBACK', 'Lab Feedback Messages', NULL, 10, 'center', 0, 0, 0);
INSERT INTO RtValueType (ValueTypeId, ValueType) VALUES (4, ' ');
INSERT INTO RtValueType (ValueTypeId, ValueType) VALUES (2, 'Float');
INSERT INTO RtValueType (ValueTypeId, ValueType) VALUES (3, 'Integer');
INSERT INTO RtValueType (ValueTypeId, ValueType) VALUES (1, 'String');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (1, 'Simple Value', 'Value');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (2, 'Output', 'Output');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (3, 'Array', 'Array');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (4, 'Timer', 'Timer');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (5, 'Input', 'Input');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (6, 'Matrix', 'Matrix');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (7, 'Recipe', 'Recipe');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (10, 'Output Ramp', 'OutputRamp');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (11, 'Group', 'Group');
INSERT INTO SfcRecipeDataType (RecipeDataTypeId, RecipeDataType, JavaClassName) VALUES (12, 'SQC', 'SQC');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (1, 'Setpoint');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (2, 'Output');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (3, 'Mode');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (4, 'Value');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (5, 'Setpoint Ramp');
INSERT INTO SfcRecipeDataOutputType (OutputTypeId, OutputType) VALUES (6, 'Output Ramp');
INSERT INTO TkLogbook (LogbookId, LogbookName) VALUES (3, 'Engineer');
INSERT INTO TkLogbook (LogbookId, LogbookName) VALUES (5, 'Test Logbook');
INSERT INTO SfcValueType (ValueTypeId, ValueType) VALUES (1, 'Float');
INSERT INTO SfcValueType (ValueTypeId, ValueType) VALUES (2, 'Integer');
INSERT INTO SfcValueType (ValueTypeId, ValueType) VALUES (3, 'String');
INSERT INTO SfcValueType (ValueTypeId, ValueType) VALUES (4, 'Boolean');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (1, 'Unit Procedure', 'com.ils.procedureStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (2, 'Operation', 'com.ils.operationStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (3, 'Phase', 'com.ils.phaseStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (4, 'Encapsulation', 'enclosing-step');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (13, 'Begin', 'begin-step');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (14, 'Action', 'action-step');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (15, 'End', 'end-step');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (16, 'None', 'None');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (17, 'Delay', 'com.ils.timedDelayStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (18, 'Yes No', 'com.ils.yesNoStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (19, 'Input', 'com.ils.inputStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (20, 'Set Queue', 'com.ils.setQueueStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (21, 'Clear Queue', 'com.ils.clearQueueStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (22, 'Queue Message', 'com.ils.queueMessageStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (23, 'Show Queue', 'com.ils.showQueueStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (24, 'Save Queue', 'com.ils.saveQueueStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (25, 'Data Entry', 'com.ils.manualDataEntryStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (26, 'Show Window', 'com.ils.showWindowStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (27, 'Print Window', 'com.ils.printWindowStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (28, 'Close Window', 'com.ils.closeWindowStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (29, 'Dialog Message', 'com.ils.dialogMessageStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (30, 'Post Delay', 'com.ils.postDelayNotification');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (31, 'Delete Delay', 'com.ils.deleteDelayNotification');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (32, 'Control Panel Message', 'com.ils.controlPanelMessageStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (33, 'Enable/Disable', 'com.ils.enableDisableStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (34, 'Select Input', 'com.ils.selectInputStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (35, 'Write Output', 'com.ils.writeOutputStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (36, 'Monitor Download', 'com.ils.monitorDownloadStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (37, 'PV Monitor', 'com.ils.pvMonitorStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (38, 'Collect Data', 'com.ils.collectDataStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (39, 'Abort', 'com.ils.abortStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (40, 'Pause', 'com.ils.pauseStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (41, 'Review Data', 'com.ils.reviewDataStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (42, 'Review With Advice', 'com.ils.reviewDataWithAdviceStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (43, 'Simple Query', 'com.ils.simpleQueryStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (45, 'Input with Limits', 'com.ils.limitedInputStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (46, 'Review Flows', 'com.ils.reviewFlowsStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (47, 'Save Data', 'com.ils.saveDataStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (48, 'Confirm Controllers', 'com.ils.confirmControllersStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (49, 'Assertion', 'assertion-step');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (50, 'com.ils.rawQueryStep', 'com.ils.rawQueryStep');
INSERT INTO SfcStepType (StepTypeId, StepType, FactoryId) VALUES (51, 'com.ils.printFileStep', 'com.ils.printFileStep');
INSERT INTO TkSite (SiteName, GatewayStartupScript, ClientStartupScript) VALUES ('Site', 'ils.demo.startup.gateway', 'ils.demo.startup.gateway');
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (1, 'dbManager', 'View', 'Recipe Family', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (2, 'dbManager', 'View', 'Value Definition', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (3, 'dbManager', 'View', 'Grade Master', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (4, 'dbManager', 'View', 'Grade Detail', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (5, 'dbManager', 'View', 'Allowed Flying Switches', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (6, 'dbManager', 'View', 'Download Log', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (7, 'dbManager', 'View', 'Events', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (8, 'dbManager', 'View', 'Gains', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (9, 'dbManager', 'View', 'SQC Limits', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (10, 'dbManager', 'View', 'Adhoc Tables', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (11, 'XOM', 'View', 'Grade History', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (13, 'XOM', 'View', 'Consoles', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (14, 'XOM', 'View', 'Logbooks', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (15, 'XOM', 'View', 'Queues', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (17, 'XOM', 'View', 'Client Isolation Settings', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (18, 'XOM', 'Admin', 'Vistalon', 0);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (19, 'XOM', 'Admin', 'Halobutyl', 0);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (20, 'dbManager', 'View', 'SQC Limits (New)', 1);
INSERT INTO TkMenuBar (Id, Application, Menu, SubMenu, Enabled) VALUES (25, 'XOM', 'View', 'Vistalon Product Mooney', 0);
INSERT INTO TkWriteLocation (WriteLocationId, Alias, ServerName, ScanClass) VALUES (4, 'EPKS', 'PKS-ASYNC', 'OPC-Fast');
INSERT INTO TkWriteLocation (WriteLocationId, Alias, ServerName, ScanClass) VALUES (5, 'LOCAL', 'LOCAL', 'OPC-Fast');
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (659, 'MOL/L', 1, 'MOLVOLC', '(DD SI) Molar Concentration', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (660, 'MKJ/T', 0, 'KBTU/LB', '(DD SI) Enthalpy per mass', 2.326, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (661, 'BBL', 0, 'VOL', '(Misc) Barrels', 0.1781190476, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (662, 'LBHR', 0, 'MFLOW', '(Misc) Pounds per hour', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (663, 'MOL/MOL', 1, 'MOL/MOL', '(DD US) Molar ratio', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (664, 'Q/R', 1, 'UA', '(DD US) UA heat transfer coefficient', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (665, 'KBTU/LB', 1, 'KBTU/LB', '(DD US) Enthalpy per hour', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (667, 'MPAD', 0, 'DPRES', '(DD SI) Delta pressure', 0.006894733261, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (668, 'PERCENT', 0, 'FRACT', '(DD US) Percent', 100, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (669, 'KBTU/MR', 1, 'ENTRO/M', '(DD US) Specific entropy', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (670, 'FRACT', 1, 'FRACT', '(DD US) Fraction', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (671, 'MBARA', 0, 'PRES', 'Milli Bar Absolute', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (672, 'KG/CM2', 0, 'PRES', 'From Blue Book', 0.070307, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (673, 'SEC', 1, 'TIME', 'Time', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (674, 'FT3/MOL', 1, 'FT3/MOL', '(DD US) Molar specific volume', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (675, 'MI', 0, 'TIME', '', 60, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (676, 'WTPCT', 0, 'FRACT', 'Variant of WtPct', 100, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (677, 'FTLB/LB', 0, 'KBTU/LB', '(DD US) Polytropic head', 777900, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (678, 'MKJ/H', 0, 'POWER', '(DD SI) Enthalpy per hour', 1.055056, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (679, 'BTU/HFR', 1, 'Th_Cond', '(DD US) Thermal conductivity', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (680, 'KG/S', 0, 'MFLOW', 'Kg per second', 0.016666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (681, 'G/H', 0, 'MFLOW', 'Grams per hour (SI)', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (682, 'PSIG', 0, 'PRES', '(Misc) Pounds per square inch gravity', 1, -14.696);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (683, 'LB/FT3', 1, 'DENSITY', '(DD US) Density', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (684, 'KJ/KG', 0, 'KBTU/LB', '(DD SI) Polytropic head', 2326, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (685, 'L', 0, 'VOL', '(DD SI) Volume', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (686, 'PPM', 0, 'FRACT', 'Parts per million', 1000000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (687, 'M', 0, 'LE', '(Misc) Meter', 0.3048, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (688, 'KG/MOL', 0, 'MOL_WT', '(Misc) Thousand MW', 0.001, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (690, 'OFFSET', 1, 'OFFSET', '(DD US) Offset', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (691, 'UMOL/L', 0, 'MOLVOLC', 'micromoles/liter', 1E-06, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (692, 'KSFT3/H', 1, 'SVFLOW', '(DD US) Volumetric flow @ 1 ATM, 60^F', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (693, 'MBTU/H', 1, 'POWER', '(DD US) Enthalpy per mass', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (694, 'KPAD', 0, 'DPRES', '(DD SI) Delta pressure', 6.894733261, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (697, 'KSFT3/M', 0, 'SVFLOW', '(Misc) Vol flow per minute', 0.01666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (698, 'CP', 1, 'VISCOS', '(DD US) Dynamic viscosity', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (699, 'MJ/H', 0, 'POWER', '(Misc) Mega Joules per hour', 1055.056, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (700, 'M^3/H', 0, 'VFLOW', 'Cubic Metres per hour, from ACFM', 1.699, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (701, 'MOLPCT', 0, 'MOL/MOL', '(Misc) Mole percent', 100, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (702, 'KG/H', 0, 'MFLOW', '(Misc) Kilograms per hour', 453.5924, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (704, 'ACFM', 0, 'VFLOW', '(Misc) Actual cubic feet per minute', 16.66666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (705, 'PCTREV', 0, 'FRACT', '(Misc) reverse acting valve', -1, 100);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (706, 'GPD', 0, 'VFLOW', '(Misc) Gallons per day', 179544, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (707, 'ATM', 0, 'PRES', '(Misc) Atmosphere (14.696 psia)', 0.06804572673, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (708, 'CAL/MOL', 0, 'KBTU/M', '(Misc) Calories per mole', 0.5559273423, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (709, 'PSID', 1, 'DPRES', '(DD US) Delta Pressure', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (710, 'PSIA', 1, 'PRES', '(DD US) Pressure', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (712, 'GPM', 0, 'VFLOW', '(Misc) Gallons per minute', 124.6833333, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (713, 'YD3', 0, 'VOL', '(Misc) Cubic yards', 0.03703703704, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (714, 'FT3/LB', 1, 'FT3/LB', '(DD US) Mass specific volume', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (716, 'KLB/H', 1, 'MFLOW', '(DD US) Mass flow', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (717, 'KHP', 0, 'POWER', '(DD US) Power', 0.3930148039, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (718, 'KG/M^3', 0, 'DENSITY', '(DD SI) Density', 16.01846, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (719, 'UST/D', 0, 'MFLOW', '(Misc) 2000 lb (US) tons per hour', 12, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (721, 'WTPPM', 0, 'M_Ratio', '(Misc) Weight parts per million', 1000000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (723, 'KMOL/H', 1, 'KMOL/H', '(DD US) Molar flow', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (725, 'BARG', 0, 'PRES', '(Misc) Bar (gage)', 0.06894733261, -1.01325);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (726, 'LB/LB', 1, 'M_Ratio', '(DD US) Mass ratio', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (727, 'BARD', 0, 'DPRES', '(Misc)  Delta pressure', 0.06894733261, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (728, 'BARA', 0, 'PRES', '(Misc) Bar (absolute)', 0.06894733261, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (729, 'BTU/LBF', 0, 'Cp', '(Misc) BTU''s per pound per deg F', 0.2388458966, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (730, 'GAL', 0, 'VOL', '(Misc) Gallons', 7.481, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (731, 'WTPPB', 0, 'M_Ratio', '(Misc) Weight parts per billion', 1000000000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (732, 'MSCFD', 0, 'SVFLOW', '(Misc) Millions of standard ft3 per day', 0.024, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (733, 'DRANKINE', 1, 'DTEMP', '(DD US) Delta temperature', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (734, 'MMHG', 0, 'PRES', '(Misc) Millimeters of mercury', 51.71474006, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (735, 'KBTU/HR', 0, 'POWER', 'Conversion from MBTU/HR to KBTU/HR', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (736, 'DKELVI', 0, 'DTEMP', '(DD SI) Delta temperature', 0.55555556, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (738, 'MOLPPM', 0, 'MOL/MOL', '(Misc) Mole parts per million', 1000000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (739, 'LB/MOL', 1, 'MOL_WT', '(DD US) Molecular weight', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (740, 'INHG', 0, 'PRES', '(Misc) Inches of mercury', 2.04176474, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (741, 'KSM^3/H', 1, 'KSM^3/H', '(DD SI) Vol Flow at 15C, 1BarA', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (742, 'FT', 1, 'LE', '(Misc) Feet', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (743, 'KM^3/H', 0, 'VFLOW', '(DD SI) Volumetric flow', 0.02831685, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (744, 'Q/K/M^2', 0, 'U', '(DD SI) U heat transfer coefficient', 20.44175, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (745, 'KCAL/MC', 0, 'ENTRO/M', '(Misc) Kilo Calories per mole per deg C', 1.000669216, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (746, 'MBARG', 0, 'PRES', 'Milli Bar Gage', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (748, 'CC/GMOL', 0, 'FT3/MOL', '(DD SI) Molar specific volume', 62.42797373, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (752, 'CAL/GK', 0, 'Cp', '(Misc) Calories per gram per deg C', 0.2390057361, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (753, 'KLB/D', 0, 'MFLOW', 'Klb per hour', 24, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (754, 'MEGWATT', 0, 'POWER', '(DD SI) Power', 0.2930711, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (755, 'MOLPPB', 0, 'MOL/MOL', '(Misc) Mole parts per billion', 1000000000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (760, 'MPA', 0, 'PRES', '(DD SI) Pressure', 0.006894733261, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (761, 'METER^3', 0, 'VOL', '(DD SI) Volume', 0.02831685, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (762, 'KT/H', 0, 'MFLOW', 'Kilo Tonne / Hour', 0.001, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (763, 'DEGC', 0, 'TEMP', '(Misc) Degrees Centigrade', 0.5555555556, -273.15);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (764, 'METER^2', 0, 'AREA', '(DD SI) Area', 0.09290304, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (766, 'KG/MI', 0, 'MFLOW', 'Kg per minute', 0.016666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (767, 'HP', 0, 'POWER', '(Misc) Horse Power', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (768, 'MKJ/K', 0, 'ENTROPY', 'Entropy', 0.0018991, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (769, 'G/CC', 0, 'DENSITY', '(Misc) Grams per cubic centimeter', 0.01601846, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (770, 'HR', 0, 'TIME', '', 3600, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (771, 'KACFM', 0, 'VFLOW', '(Misc) Thousands of ACFM', 0.01666666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (772, 'KCAL/M', 0, 'KBTU/M', '(Misc) Kilo Calories per mole', 0.0005559273423, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (773, 'RANKINE', 1, 'TEMP', '(DD US) Absolute temperature', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (774, 'Q/R/FT2', 1, 'U', '(DD US) U heat transfer coefficient', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (776, 'NONE', 1, 'NONE', 'For no conversion', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (780, 'FT3', 1, 'VOL', '(DD US) Volume', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (781, 'KJ/MOLK', 0, 'ENTRO/M', '(DD SI) Specific entropy', 4.1868, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (782, 'FT2', 1, 'AREA', '(DD US) Area', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (784, 'MOL/M3', 0, 'MOLVOLC', '(SI) Mols per cubic meter', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (785, 'SEC/10', 0, 'TIME', '', 10, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (786, 'SCFM', 0, 'SVFLOW', '(Misc) Std Cu Ft per minute', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (787, 'AMPS', 1, 'CURRENT', '', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (789, 'CC/GM', 0, 'FT3/LB', '(DD SI) Mass specific volume', 62.42797373, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (790, 'KELVI', 0, 'TEMP', '(DD SI) Absolute temperature', 0.5555555556, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (791, 'SLOPE', 1, 'SLOPE', '(DD US) Slope', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (793, 'DEGF', 0, 'TEMP', '(Misc) Degrees Fahrenheit', 1, -459.67);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (794, 'MKJ/H/K', 0, 'UA', '(DD SI) UA heat transfer coefficient', 1.899100718, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (796, 'INH2O', 0, 'PRES', '(Misc) Inches of water', 27.70749582, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (797, 'RATIO', 1, 'RATIO', '(Misc) Ratio''s; e.g., CP/CV ratio', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (798, 'T/H', 0, 'MFLOW', '(DD SI) Mass flow', 0.4535924, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (802, 'PHR', 1, 'PHR', 'Pounds per Hundred pounds Rubber', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (804, 'KG', 0, 'MASS', '(Misc) Kilograms', 0.4535924, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (807, 'KCAL/G', 0, 'KBTU/LB', '(Misc) Kilo Calories per gram', 0.5559273423, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (809, 'KJ/GMOL', 0, 'KBTU/M', '(DD SI) Specific enthalpy', 2.326, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (812, 'KRPM', 1, 'KRPM', '(DD US) Rotational speed', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (813, 'MG/MOL', 0, 'MOL_WT', '(Misc) Million MW', 1E-06, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (815, 'KFT3/H', 1, 'VFLOW', '(DD US) Volumetric flow', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (817, 'LBM', 1, 'MASS', '(Misc) Pounds', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (818, 'KJ/KGK', 1, 'Cp', '(Misc) Kilo Joules per kg per deg K', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (819, 'CAL/MC', 0, 'ENTRO/M', '(Misc) Calories per mole per deg C', 1000.669216, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (820, 'BTU/LB', 0, 'KBTU/LB', 'BTU per pound', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (823, 'TONS', 0, 'MASS', '(Misc) US short (2000lb) Tons', 0.0005, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (825, 'IN2', 0, 'AREA', '(Misc) Square inch', 144, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (826, 'W/M/K', 0, 'Th_Cond', '(DD SI) Thermal conductivity', 1.730735, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (828, 'BPD', 0, 'VFLOW', '(Misc) Barrels per day', 4274.857143, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (830, 'KJ/K', 0, 'ENTROPY', '(DD SI) Entropy', 1E-06, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (833, 'KJ/H', 0, 'POWER', '(Misc) Kilo Joules per hour', 1055056, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (834, 'BPH', 0, 'VFLOW', 'Barrels per hour', 0.0416666667, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (836, 'RPM', 0, 'KRPM', '(Misc) Revolutions per minute', 1000, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (837, 'KBTU/M', 1, 'KBTU/M', '(DD US) Specific enthalpy', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (842, 'INHGV', 0, 'PRES', '(Misc) Inches of mercury vacuum', -2.04176474, 30.00577461);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (843, 'KWATT', 0, 'POWER', '(Misc) Kilowatts', 293.0711, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (844, 'KBTU/R', 1, 'ENTROPY', '(DD US) Entropy', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (845, 'CAL/G', 0, 'KBTU/LB', '(Misc) Calories per gram', 555.9273423, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (847, 'MMOL/H', 1, 'MMOL/H', '(DD SI) Molar flow', 0, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (848, 'LB/GAL', 0, 'DENSITY', '(Misc) Pounds per gallon', 0.133671969, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (851, 'T/DAY', 0, 'MFLOW', 'Tonne / Day', 24, 0);
INSERT INTO Units (id, name, isBaseUnit, type, description, m, b) VALUES (852, 'MMOL/L', 0, 'MOLVOLC', 'millimoles/liter', 0.001, 0);
INSERT INTO Version (VersionId, Version, ReleaseDate, InstallDate) VALUES (0, '1.0r0     ', '2016-10-12 13:00:00', '2016-11-03 12:00:00');
INSERT INTO Version (VersionId, Version, ReleaseDate, InstallDate) VALUES (1, '1.1r0     ', '2017-10-12 13:00:00', '2017-11-03 12:00:00');
INSERT INTO Version (VersionId, Version, ReleaseDate, InstallDate) VALUES (2, '1.2r0     ', '2018-10-12 13:00:00', '2018-11-03 12:00:00');
INSERT INTO Version (VersionId, Version, ReleaseDate, InstallDate) VALUES (3, '1.3r0     ', '2019-10-12 13:00:00', '2019-11-03 12:00:00');
INSERT INTO Version (VersionId, Version, ReleaseDate, InstallDate) VALUES (4, '1.4r0     ', '2020-10-12 13:00:00', '2020-11-03 12:00:00');
INSERT INTO UnitAliases (id, alias, name) VALUES (145, 'GJ/T', 'MKJ/T');
INSERT INTO UnitAliases (id, alias, name) VALUES (146, 'LB/HR', 'LBHR');
INSERT INTO UnitAliases (id, alias, name) VALUES (147, 'LBS/H', 'LBHR');
INSERT INTO UnitAliases (id, alias, name) VALUES (148, '>MPA', 'MPAD');
INSERT INTO UnitAliases (id, alias, name) VALUES (150, 'GJ/H', 'MKJ/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (151, 'G-H', 'G/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (152, 'LBCUFT', 'LB/FT3');
INSERT INTO UnitAliases (id, alias, name) VALUES (153, 'MJ/T', 'KJ/KG');
INSERT INTO UnitAliases (id, alias, name) VALUES (154, '>KPA', 'KPAD');
INSERT INTO UnitAliases (id, alias, name) VALUES (155, 'LB-HR', 'LBHR');
INSERT INTO UnitAliases (id, alias, name) VALUES (156, 'KLB/HR', 'KLB/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (157, 'TONS/D', 'UST/D');
INSERT INTO UnitAliases (id, alias, name) VALUES (158, 'GR/HR', 'G/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (159, 'KLBS/H', 'KLB/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (160, 'PSI', 'PSIA');
INSERT INTO UnitAliases (id, alias, name) VALUES (161, 'KG/KG', 'LB/LB');
INSERT INTO UnitAliases (id, alias, name) VALUES (162, 'DDEGF', 'DRANKINE');
INSERT INTO UnitAliases (id, alias, name) VALUES (163, 'DDEGC', 'DKELVI');
INSERT INTO UnitAliases (id, alias, name) VALUES (164, 'PCT', 'PERCENT');
INSERT INTO UnitAliases (id, alias, name) VALUES (165, 'KG/KGM', 'LB/MOL');
INSERT INTO UnitAliases (id, alias, name) VALUES (166, '>BAR', 'MPAD');
INSERT INTO UnitAliases (id, alias, name) VALUES (167, 'MWATT', 'MEGWATT');
INSERT INTO UnitAliases (id, alias, name) VALUES (168, 'WTFRACT', 'FRACT');
INSERT INTO UnitAliases (id, alias, name) VALUES (169, 'FRACT', 'FRACT');
INSERT INTO UnitAliases (id, alias, name) VALUES (170, 'KLBPH', 'KLB/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (171, 'KLB-HR', 'KLB/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (172, 'MOLWT', 'LB/MOL');
INSERT INTO UnitAliases (id, alias, name) VALUES (173, 'DEGR', 'RANKINE');
INSERT INTO UnitAliases (id, alias, name) VALUES (174, 'DEGK', 'KELVI');
INSERT INTO UnitAliases (id, alias, name) VALUES (175, 'KG/GMOL', 'KG/MOL');
INSERT INTO UnitAliases (id, alias, name) VALUES (176, 'MBTUHR', 'MBTU/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (177, 'T/T', 'LB/LB');
INSERT INTO UnitAliases (id, alias, name) VALUES (178, 'PERCNT', 'PERCENT');
INSERT INTO UnitAliases (id, alias, name) VALUES (179, '#/H', 'LBHR');
INSERT INTO UnitAliases (id, alias, name) VALUES (180, 'FT**3', 'FT3');
INSERT INTO UnitAliases (id, alias, name) VALUES (181, 'USGAL', 'GAL');
INSERT INTO UnitAliases (id, alias, name) VALUES (182, 'M2', 'METER^2');
INSERT INTO UnitAliases (id, alias, name) VALUES (183, 'M3', 'METER^3');
INSERT INTO UnitAliases (id, alias, name) VALUES (184, 'MG/GMOL', 'MG/MOL');
INSERT INTO UnitAliases (id, alias, name) VALUES (185, 'KLBHR', 'KLB/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (186, 'KSCF/M', 'KSFT3/M');
INSERT INTO UnitAliases (id, alias, name) VALUES (187, 'GJ/HK', 'MKJ/H/K');
INSERT INTO UnitAliases (id, alias, name) VALUES (188, 'KSCF/H', 'KSFT3/H');
INSERT INTO UnitAliases (id, alias, name) VALUES (189, '>PSI', 'PSID');
INSERT INTO UnitAliases (id, alias, name) VALUES (190, '>RANKINE', 'DRANKINE');
INSERT INTO UnitAliases (id, alias, name) VALUES (191, 'DEG-F', 'DEGF');
INSERT INTO UnitAliases (id, alias, name) VALUES (192, '>DEGC', 'DKELVI');
INSERT INTO UnitAliases (id, alias, name) VALUES (193, 'G/GMOL', 'LB/MOL');
INSERT INTO UnitAliases (id, alias, name) VALUES (194, 'KBTU/H', 'KBTU/HR');
INSERT INTO UnitAliases (id, alias, name) VALUES (195, '>DEGF', 'DRANKINE');
INSERT INTO UnitAliases (id, alias, name) VALUES (196, '>KELVI', 'DKELVI');
INSERT INTO UnitAliases (id, alias, name) VALUES (197, 'G/HR', 'G/H');
INSERT INTO TkPost (PostId, Post, MessageQueueId, LogbookId, DownloadActive) VALUES (70, 'Test', 15, 5, 0);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (1, 'GroupRampMethod', 'None', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (2, 'GroupRampMethod', 'Shortest', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (5, 'FeedbackMethod', 'Simple Sum', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (6, 'FeedbackMethod', 'Average', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (9, 'FeedbackMethod', 'Most Positive', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (10, 'FeedbackMethod', 'Most Negative', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (12, 'RtLimitType', 'SQC', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (13, 'RtLimitType', 'Validity', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (14, 'RtLimitType', 'Release', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (15, 'RtLimitSource', 'Constant', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (16, 'RtLimitSource', 'Recipe', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (17, 'RtLimitSource', 'DCS', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (18, 'GroupRampMethod', 'Longest', 'None', 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (23, 'LtSelTargetType', 'PHD Lab Value Item Id', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (24, 'LtSelTargetType', 'PHD Lab Value Interface', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (25, 'WindowPosition', 'center', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (26, 'WindowPosition', 'topLeft', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (27, 'WindowPosition', 'topCenter', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (28, 'WindowPosition', 'topRight', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (29, 'WindowPosition', 'bottomLeft', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (30, 'WindowPosition', 'bottomCenter', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (31, 'WindowPosition', 'bottomRight', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (32, 'RampType', 'Time', NULL, 1);
INSERT INTO Lookup (LookupId, LookupTypeCode, LookupName, LookupDescription, Active) VALUES (33, 'RampType', 'Rate', NULL, 1);
INSERT INTO TkUnit (UnitId, UnitName, UnitPrefix, UnitAlias, PostId, Grade) VALUES (74, 'Test', NULL, NULL, 70, NULL);
INSERT INTO TkConsole (ConsoleId, WindowName, ConsoleName, Priority, PostId) VALUES (1743, 'Demo/Test Console', 'Test Console', 1, 70);
